dist: xenial
services:
  - postgresql
addons:
  postgresql: "9.4"
before_script:
  - psql -U postgres -c "create user prueba password 'prueba'"
  - psql -U postgres -c "create database test_prueba owner prueba"
  - psql -U postgres -c "ALTER USER prueba CREATEDB"
  - psql -U postgres -c "ALTER ROLE prueba Superuser"
language: python
python:
  - "3.8"
install:
  - pip install -r requirements.txt
  - pip install codacy-coverage
script:
  - coverage run --branch --source=. ./manage.py test
  - coverage xml
  - python-codacy-coverage -r coverage.xml
