# Generated by Django 3.1.4 on 2021-11-08 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Liga', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('escudo', models.CharField(max_length=200)),
                ('partidosJugados', models.IntegerField()),
                ('victorias', models.IntegerField()),
                ('derrotas', models.IntegerField()),
                ('empates', models.IntegerField()),
                ('golesFavor', models.IntegerField()),
                ('golesContra', models.IntegerField()),
                ('puntos', models.IntegerField()),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Liga.liga')),
            ],
        ),
    ]
