# Generated by Django 3.1.4 on 2021-11-08 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Jugador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadisticasCreacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasesGol', models.IntegerField()),
                ('pasesMuertosGol', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EstadisticasDefensa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entradas', models.IntegerField()),
                ('entradasAtaque', models.IntegerField()),
                ('entradasMedio', models.IntegerField()),
                ('entradasDefensa', models.IntegerField()),
                ('entradasGanadas', models.IntegerField()),
                ('presion', models.IntegerField()),
                ('presionAtaque', models.IntegerField()),
                ('presionMedio', models.IntegerField()),
                ('presionGanada', models.IntegerField()),
                ('presionDefensa', models.IntegerField()),
                ('intentoRegate', models.IntegerField()),
                ('regateParado', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EstadisticasDiversas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balonesAereosGanados', models.IntegerField()),
                ('balonesAereosPerdidos', models.IntegerField()),
                ('balonesSueltosRecuperados', models.IntegerField()),
                ('amarillas', models.IntegerField()),
                ('dobleAmarillas', models.IntegerField()),
                ('rojas', models.IntegerField()),
                ('faltasRecibidas', models.IntegerField()),
                ('faltasCometidas', models.IntegerField()),
                ('fueraJuego', models.IntegerField()),
                ('penaltiesConcedidos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EstadisticasGenerales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partidosJugados', models.IntegerField()),
                ('titular', models.IntegerField()),
                ('partidosCompletos', models.IntegerField()),
                ('entraSuplente', models.IntegerField()),
                ('goles', models.IntegerField()),
                ('minutosJugados', models.IntegerField()),
                ('asistencias', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EstadisticasPases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distanciaPases', models.IntegerField()),
                ('pasesCortos', models.IntegerField()),
                ('pasesCortosEfectivos', models.IntegerField()),
                ('pasesMedios', models.IntegerField()),
                ('pasesMediosEfectivos', models.IntegerField()),
                ('pasesLargos', models.IntegerField()),
                ('pasesLargosEfectivos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EstadisticasPortero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('golesRecibidos', models.IntegerField()),
                ('tirosRecibidos', models.IntegerField()),
                ('paradasRecibidos', models.IntegerField()),
                ('cleanSheet', models.IntegerField()),
                ('penaltiesEncajados', models.IntegerField()),
                ('penaltiesParados', models.IntegerField()),
                ('penaltiesFalladosContrario', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EstadisticasRegates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balonTocadoAreaPenaltyPropia', models.IntegerField()),
                ('balonTocadoDefensa', models.IntegerField()),
                ('balonTocadoMedio', models.IntegerField()),
                ('balonTocadoAtaque', models.IntegerField()),
                ('balonTocadoAreaPenaltyContr', models.IntegerField()),
                ('regates', models.IntegerField()),
                ('regatesCompletados', models.IntegerField()),
                ('controles', models.IntegerField()),
                ('distanciaPosesion', models.IntegerField()),
                ('controlesFallidos', models.IntegerField()),
                ('pasesObjetivo', models.IntegerField()),
                ('pasesRecibidos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EstadisticasTipoPases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conPresion', models.IntegerField()),
                ('centros', models.IntegerField()),
                ('pasesPieDerecho', models.IntegerField()),
                ('pasesPieIzquierdo', models.IntegerField()),
                ('pasesCabeza', models.IntegerField()),
                ('cornersLanzados', models.IntegerField()),
                ('pasesFueraJuego', models.IntegerField()),
                ('pasesFueraCampo', models.IntegerField()),
                ('paseSuelo', models.IntegerField()),
                ('paseBajo', models.IntegerField()),
                ('paseAlto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EstadisticasTiros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiros', models.IntegerField()),
                ('tirosPorteria', models.IntegerField()),
                ('distanciaTiros', models.FloatField()),
                ('tirosFalta', models.IntegerField()),
                ('penalties', models.IntegerField()),
                ('penaltiesMarcados', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EstadisticasJugador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temporada', models.CharField(max_length=30, null=True)),
                ('equipo', models.CharField(max_length=80, null=True)),
                ('estadisticasCreacion', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Estadisticas.estadisticascreacion')),
                ('estadisticasDefensa', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Estadisticas.estadisticasdefensa')),
                ('estadisticasDiversas', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Estadisticas.estadisticasdiversas')),
                ('estadisticasGenerales', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Estadisticas.estadisticasgenerales')),
                ('estadisticasPases', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Estadisticas.estadisticaspases')),
                ('estadisticasPortero', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Estadisticas.estadisticasportero')),
                ('estadisticasRegates', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Estadisticas.estadisticasregates')),
                ('estadisticasTipoPases', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Estadisticas.estadisticastipopases')),
                ('estadisticasTiros', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Estadisticas.estadisticastiros')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jugador.jugador')),
            ],
        ),
    ]
