# Generated by Django 3.1.4 on 2021-11-08 21:22

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Equipo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('nombreCompleto', models.CharField(max_length=80)),
                ('nacionalidad', models.CharField(max_length=40)),
                ('fechaDeNacimiento', models.DateField(null=True)),
                ('altura', models.FloatField(null=True)),
                ('peso', models.FloatField(null=True)),
                ('pie', models.CharField(choices=[('Izquierda', 'Zurdo'), ('Derecha', 'Diestro'), ('Ambos', 'Ambidiestro')], max_length=10)),
                ('posicion', models.CharField(choices=[('PO', 'Portero'), ('DF', 'Defensa'), ('CC', 'CentroCampista'), ('DL', 'Delantero')], max_length=2)),
                ('demarcaciones', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=3), null=True, size=None)),
                ('foto', models.CharField(max_length=150)),
                ('equipoActual', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Equipo.equipo')),
            ],
        ),
    ]
